package Helpers;

public enum CellType {
	TOP_LEFT_CORNER, TOP_SIDE, TOP_RIGHT_CORNER, 
	TOP_RIGHT_SIDE, RIGHT_CORNER, BOTTOM_RIGHT_SIDE, 
	BOTTOM_RIGHT_CORNER, BOTTOM_SIDE, BOTTOM_LEFT_CORNER, 
	BOTTOM_LEFT_SIDE, LEFT_CORNER, TOP_LEFT_SIDE,
	CENTER
}
